### ISSUE TITLE
TODO count 46 / FIXME Count 2

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/edv-client#20]
- [ ] TODO: only polyfill the missing functions
       Commit: (30e9132) Add stream support.
       File:  [util-browser.js:14](https://github.com/digitalbazaar/edv-client/blob/master/util-browser.js#L14)
       Dave Longley commented 6 months ago

  - [ ] TODO: ensure this polyfill is necessary
       Commit: (30e9132) Add stream support.
       File:  [util-browser.js:9](https://github.com/digitalbazaar/edv-client/blob/master/util-browser.js#L9)
       Dave Longley commented 6 months ago

  - [ ] TODO: implement
       Commit: (1a0b16f) Update testing.
       File:  [tests/MockStorage.js:52](https://github.com/digitalbazaar/edv-client/blob/master/tests/MockStorage.js#L52)
       David I. Lehn commented 9 months ago

  - [ ] TODO: validate `config`
       Commit: (1a0b16f) Update testing.
       File:  [tests/MockStorage.js:26](https://github.com/digitalbazaar/edv-client/blob/master/tests/MockStorage.js#L26)
       David I. Lehn commented 9 months ago

  - [ ] TODO: add more tests: getAll, update, setStatus
       Commit: (9e43f9c) Refactor API to work better with capabilities.
       File:  [tests/10-DataHubClient.spec.js:181](https://github.com/digitalbazaar/edv-client/blob/master/tests/10-DataHubClient.spec.js#L181)
       Dave Longley commented 8 months ago

  - [ ] TODO: Explain what 'referenceId' is
       Commit: (9e43f9c) Refactor API to work better with capabilities.
       File:  [README.md:87](https://github.com/digitalbazaar/edv-client/blob/master/README.md#L87)
       Dave Longley commented 8 months ago

  - [ ] TODO: is sequence required?
       Commit: (720f280) Add core files.
       File:  [README.md:85](https://github.com/digitalbazaar/edv-client/blob/master/README.md#L85)
       Dave Longley commented 9 months ago

  - [ ] TODO: explain EDV service must be able to authenticate user
       Commit: (b7f65f6) Finish rename to edv-client.
       File:  [README.md:81](https://github.com/digitalbazaar/edv-client/blob/master/README.md#L81)
       Dave Longley commented 4 months ago

  - [ ] TODO: create keystore for controllerKey and update
       Commit: (12670ce) Replace direct KEK with key agreement support.
       File:  [README.md:70](https://github.com/digitalbazaar/edv-client/blob/master/README.md#L70)
       Dave Longley commented 6 months ago

  - [ ] (TODO: show a simpler local example):
       Commit: (12670ce) Replace direct KEK with key agreement support.
       File:  [README.md:49](https://github.com/digitalbazaar/edv-client/blob/master/README.md#L49)
       Dave Longley commented 6 months ago

  - [ ] TODO: determine if there's a cleaner way to do this that maintains
       Commit: (1d0b681) Auto-parse doc ID from capability.
       File:  [DataHubDocument.js:46](https://github.com/digitalbazaar/edv-client/blob/master/DataHubDocument.js#L46)
       Dave Longley commented 7 months ago

  - [ ] TODO: use ocapld.getTarget() utility function?
       Commit: (ce6b232) Use zcap invocation target for document URL if present.
       File:  [DataHubClient.js:1024](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L1024)
       Dave Longley commented 7 months ago

  - [ ] TODO: validate response.data
       Commit: (30e9132) Add stream support.
       File:  [DataHubClient.js:1017](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L1017)
       Dave Longley commented 6 months ago

  - [ ] TODO: await digest from tee'd stream
       Commit: (30e9132) Add stream support.
       File:  [DataHubClient.js:946](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L946)
       Dave Longley commented 6 months ago

  - [ ] TODO: in theory could do encryption and sending in parallel, they
       Commit: (30e9132) Add stream support.
       File:  [DataHubClient.js:941](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L941)
       Dave Longley commented 6 months ago

  - [ ] // TODO: tee `stream` to digest stream as well
       Commit: (30e9132) Add stream support.
       File:  [DataHubClient.js:914](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L914)
       Dave Longley commented 6 months ago

  - [ ] FIXME: add ability to disable EDV access or to revoke all ocaps
       Commit: (b7f65f6) Finish rename to edv-client.
       File:  [EdvClient.js:760](https://github.com/digitalbazaar/edv-client/blob/master/EdvClient.js#L760)
       Dave Longley commented 4 months ago

  - [ ] TODO: add `capability` and `invocationSigner` support?
       Commit: (35950eb) Add http-signature support for document APIs.
       File:  [DataHubClient.js:759](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L759)
       Dave Longley commented 7 months ago

  - [ ] TODO: add `capability` and `invocationSigner` support?
       Commit: (35950eb) Add http-signature support for document APIs.
       File:  [DataHubClient.js:734](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L734)
       Dave Longley commented 7 months ago

  - [ ] TODO: add `capability` and `invocationSigner` support?
       Commit: (35950eb) Add http-signature support for document APIs.
       File:  [DataHubClient.js:714](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L714)
       Dave Longley commented 7 months ago

  - [ ] TODO: more robustly validate `config` (`keyAgreementKey`,
       Commit: (12670ce) Replace direct KEK with key agreement support.
       File:  [DataHubClient.js:646](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L646)
       Dave Longley commented 6 months ago

  - [ ] TODO: should `delete` be used here as a separate action?
       Commit: (ffab708) Add methods to enable/disable zcaps.
       File:  [DataHubClient.js:617](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L617)
       Dave Longley commented 7 months ago

  - [ ] TODO: should `delete` be used here as a separate action?
       Commit: (35950eb) Add http-signature support for document APIs.
       File:  [DataHubClient.js:367](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L367)
       Dave Longley commented 7 months ago

  - [ ] TODO: support passing cipher `version`
       Commit: (720f280) Add core files.
       File:  [DataHubClient.js:53](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L53)
       Dave Longley commented 9 months ago

       TODO Count          46
       FIXME Count         2
       Oldest Comment      9 months ago
       Oldest Commenter    Dave Longley
       Oldest Comment      TODO: is sequence required?

**Comment by JSAssassin** [comment]
New Report #58
