### ISSUE TITLE
TODO/FIXME Count 29

### ISSUE THREAD

**Issue by JSAssassin** [digitalbazaar/edv-client#58]
- [ ] TODO: only polyfill the missing functions
       Commit: (30e9132) Add stream support.
       [util-browser.js:14](https://github.com/digitalbazaar/edv-client/blob/master/util-browser.js#L14)
       Dave Longley commented 10 months ago

  - [ ] TODO: ensure this polyfill is necessary
       Commit: (30e9132) Add stream support.
       [util-browser.js:9](https://github.com/digitalbazaar/edv-client/blob/master/util-browser.js#L9)
       Dave Longley commented 10 months ago

  - [ ] TODO: implement
      Commit: (1a0b16f) Update testing.
      [tests/MockStorage.js:111](https://github.com/digitalbazaar/edv-client/blob/master/tests/MockStorage.js#L111)
      David I. Lehn commented a year ago

  - [ ] TODO: validate `config`
      Commit: (1a0b16f) Update testing.
      [tests/MockStorage.js:85](https://github.com/digitalbazaar/edv-client/blob/master/tests/MockStorage.js#L85)
      David I. Lehn commented a year ago

  - [ ] FIXME: headers should not be nested like this, see issue #37
      Commit: (855b967) Implement revokeCapability API.
      [tests/MockStorage.js:54](https://github.com/digitalbazaar/edv-client/blob/master/tests/MockStorage.js#L54)
      Matthew Collier commented 3 months ago

  - [ ] FIXME: enableCapability is being deprecated.
      Commit: (2ef921c) Add deprecation notice to tests.
      [tests/30-EdvRecipients.spec.js:250](https://github.com/digitalbazaar/edv-client/blob/master/tests/30-EdvRecipients.spec.js#L250)
      Andrew Jones commented 4 months ago

  - [ ] FIXME: enableCapability is being deprecated.
      Commit: (2ef921c) Add deprecation notice to tests.
      [tests/30-EdvRecipients.spec.js:179](https://github.com/digitalbazaar/edv-client/blob/master/tests/30-EdvRecipients.spec.js#L179)
      Andrew Jones commented 4 months ago

  - [ ] TODO: add more tests: getAll, update, setStatus
      Commit: (9e43f9c) Refactor API to work better with capabilities.
      [tests/10-DataHubClient.spec.js:188](https://github.com/digitalbazaar/edv-client/blob/master/tests/10-DataHubClient.spec.js#L188)
      Dave Longley commented a year ago

  - [ ] TODO: Explain what 'referenceId' is
       Commit: (a4040ec) Add url example to create and register section of readme
       File:  [README.md:130](https://github.com/digitalbazaar/edv-client/blob/master/README.md#L130)
       Orie Steele commented 3 months ago

  - [x] TODO: is sequence required?
       Commit: (a4040ec) Add url example to create and register section of readme
       File:  [README.md:128](https://github.com/digitalbazaar/edv-client/blob/master/README.md#L128)
       Orie Steele commented 3 months ago

  - [ ] TODO: explain EDV service must be able to authenticate user
       Commit: (a4040ec) Add url example to create and register section of readme
       File:  [README.md:124](https://github.com/digitalbazaar/edv-client/blob/master/README.md#L124)
       Orie Steele commented 3 months ago

  - [ ] TODO: Explain what 'referenceId' is
       Commit: (9e43f9c) Refactor API to work better with capabilities.
       File:  [README.md:108](https://github.com/digitalbazaar/edv-client/blob/master/README.md#L108)
       Dave Longley commented a year ago

  - [x] TODO: is sequence required?
       Commit: (720f280) Add core files.
       File:  [README.md:106](https://github.com/digitalbazaar/edv-client/blob/master/README.md#L106)
       Dave Longley commented a year ago

  - [ ] TODO: explain EDV service must be able to authenticate user
       Commit: (b7f65f6) Finish rename to edv-client.
       File:  [README.md:102](https://github.com/digitalbazaar/edv-client/blob/master/README.md#L102)
       Dave Longley commented 9 months ago

  - [ ] TODO: show a simpler local example:
       Commit: (12670ce) Replace direct KEK with key agreement support.
       File:  [README.md:49](https://github.com/digitalbazaar/edv-client/blob/master/README.md#L49)
       Dave Longley commented 10 months ago

  - [ ] TODO: determine if there's a cleaner way to do this that maintains
      Commit: (1d0b681) Auto-parse doc ID from capability.
      [DataHubDocument.js:45](https://github.com/digitalbazaar/edv-client/blob/master/DataHubDocument.js#L45)
      Dave Longley commented a year ago

  - [ ] TODO: use ocapld.getTarget() utility function?
      Commit: (ce6b232) Use zcap invocation target for document URL if present.
      [DataHubClient.js:1168](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L1168)
      Dave Longley commented a year ago

  - [ ] TODO: validate response.data
      Commit: (30e9132) Add stream support.
      [DataHubClient.js:1161](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L1161)
      Dave Longley commented 10 months ago

  - [ ] TODO: await digest from tee'd stream
      Commit: (30e9132) Add stream support.
      [DataHubClient.js:1090](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L1090)
      Dave Longley commented 10 months ago

  - [ ] TODO: in theory could do encryption and sending in parallel, they
      Commit: (30e9132) Add stream support.
      [DataHubClient.js:1085](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L1085)
      Dave Longley commented 10 months ago

  - [ ] TODO: tee `stream` to digest stream as well
      Commit: (30e9132) Add stream support.
      [DataHubClient.js:1058](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L1058)
      Dave Longley commented 10 months ago

  - [ ] FIXME: add ability to disable EDV access or to revoke all ocaps
       Commit: (b7f65f6) Finish rename to edv-client.
       [EdvClient.js:860](https://github.com/digitalbazaar/edv-client/blob/master/EdvClient.js#L860)
       Dave Longley commented 9 months ago

  - [ ] TODO: add `capability` and `invocationSigner` support?
      Commit: (35950eb) Add http-signature support for document APIs.
      [DataHubClient.js:859](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L859)
      Dave Longley commented a year ago

  - [ ] TODO: add `capability` and `invocationSigner` support?
      Commit: (35950eb) Add http-signature support for document APIs.
      [DataHubClient.js:832](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L832)
      Dave Longley commented a year ago

  - [ ] TODO: add `capability` and `invocationSigner` support?
      Commit: (35950eb) Add http-signature support for document APIs.
      [DataHubClient.js:810](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L810)
      Dave Longley commented a year ago

  - [ ] TODO: more robustly validate `config` (`keyAgreementKey`,
      Commit: (12670ce) Replace direct KEK with key agreement support.
      [DataHubClient.js:664](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L664)
      Dave Longley commented 10 months ago

  - [ ] TODO: should `delete` be used here as a separate action?
      Commit: (ffab708) Add methods to enable/disable zcaps.
      [DataHubClient.js:626](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L626)
      Dave Longley commented a year ago

  - [ ] TODO: should `delete` be used here as a separate action?
      Commit: (35950eb) Add http-signature support for document APIs.
      [DataHubClient.js:374](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L374)
      Dave Longley commented a year ago

  - [ ] TODO: support passing cipher `version`
      Commit: (720f280) Add core files.
      [DataHubClient.js:57](https://github.com/digitalbazaar/edv-client/blob/master/DataHubClient.js#L57)
      Dave Longley commented a year ago

**Comment by dlongley** [comment]
Closing as out-of-date with other issues filed covering any important topics.
